
output: LinkedList.o Reverese_A_Linked_LIst_Neet_Code_150.o
	g++ LinkedList.o Reverese_A_Linked_LIst_Neet_Code_150.o -o output

Reverese_A_Linked_LIst_Neet_Code_150.o: Reverese_A_Linked_LIst_Neet_Code_150.cpp
	g++ -c Reverese_A_Linked_LIst_Neet_Code_150.cpp

LinkedList.o: LinkedList.cpp LinkedList.h
	g++ -c LinkedList.cpp

clean: 
	rm *.o output
